name: Testing

on: [pull_request]

jobs:
  matlab-tests:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests
        id: matlab-test
        run: |
          TEST_RESULTS=$(/usr/local/bin/matlab -nodisplay -nosplash -nodesktop -r "addpath(genpath('.')); cd('testing/unit_tests'); runtests(struct2table(dir('*.m')).name); exit;")
          PARSED_RESULTS=$(echo $TEST_RESULTS | awk -F'com\.' '{ n = split($2, v, "(___+)|(===+)|(---+)"); for (i = 0; ++i <= n;) { print v[i] } }')
          echo ::set-output name=results::$PARSED_RESULTS

      - name: Post comment
        uses: NejcZdovc/comment-pr@v1
        with:
          file: "testing-comment.md"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          TEST_RESULTS: ${{steps.matlab-test.outputs.results}}
          GH_ACTION_RUN: ${{github.run_id}}
